# Generated by Django 3.0.6 on 2020-07-13 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Non Binary'), ('na', 'Prefer not to say')], max_length=2)),
                ('bio', models.TextField()),
                ('tshirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='T-Shirt Size')),
                ('skills', models.TextField()),
                ('educational_institution', models.CharField(max_length=128)),
                ('field_of_study', models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('ec', 'Electronics and Communication'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('ee', 'Electrical and Electronis Engineering'), ('it', 'Information Technology')], max_length=64, verbose_name='Field of Study')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
