# Generated by Django 3.0.6 on 2020-05-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='email',
            field=models.EmailField(default='a@ex.com', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='email',
            field=models.EmailField(default='a@ex.com', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
