# Generated by Django 3.0.6 on 2020-11-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='is_ieee',
            field=models.BooleanField(default=False, verbose_name='Are you an IEEE member?'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='shipping_address',
            field=models.TextField(default=' '),
        ),
    ]
