# Generated by Django 3.0.6 on 2020-11-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201119_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='educational_status',
            field=models.CharField(default='Bachelors', max_length=12),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='state',
            field=models.CharField(default='Kerala', max_length=41, verbose_name='State/Province of Residence'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='team_status',
            field=models.CharField(default='Has Team', max_length=10),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='year_of_graduation',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2023),
        ),
    ]
