# Generated by Django 3.0.6 on 2020-07-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200617_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='email',
        ),
    ]
