# Generated by Django 3.0.6 on 2020-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201120_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='educational_status',
            field=models.CharField(choices=[('High School', 'High School'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='Bachelors', max_length=12),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='state',
            field=models.CharField(choices=[('Outside India', 'Outside India'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman And Nicobar Islands', 'Andaman And Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra And Nagar Haveli And Daman And Diu', 'Dadra And Nagar Haveli And Daman And Diu'), ('Delhi', 'Delhi'), ('Jammu And Kashmir', 'Jammu And Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], default='Kerala', max_length=41, verbose_name='State/Province of Residence'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='team_status',
            field=models.CharField(choices=[('No Team', 'I want to participate alone'), ('Need Team', "I would like to participate as a team, but I haven't found a team yet"), ('Has Team', 'I would like to participate as a team and I already have a team.')], default='Has Team', max_length=10),
        ),
    ]
