# Generated by Django 3.0.6 on 2020-11-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201120_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='is_ieee',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Are you an IEEE member?'),
        ),
    ]
