# Generated by Django 3.0.6 on 2020-11-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='field_of_study',
            field=models.CharField(choices=[('School', 'School Student'), ('BSc', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BTech', 'Bachelor of Technology'), ('BCom', 'Bachelor of Commerce'), ('MSc', 'Master of Science'), ('MA', 'Master of Arts'), ('MTech', 'Master of Technology'), ('MCom', 'Master of Commerce'), ('Other', 'Other')], default='BTech', max_length=8, verbose_name='Field of Study'),
        ),
    ]
