# Generated by Django 3.0.6 on 2020-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201122_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='website_link',
            field=models.URLField(blank=True, verbose_name='Personal Website Link'),
        ),
    ]
