# Generated by Django 3.0.6 on 2020-11-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_participantprofile_avatar_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='welcome_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
