# Generated by Django 3.0.6 on 2020-12-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_participantprofile_welcome_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='pin_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
