# Generated by Django 3.0.6 on 2020-12-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20201208_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='field_of_study',
            field=models.CharField(choices=[('School Student', 'School Student'), ('Science', 'Science'), ('Arts', 'Arts'), ('Engineering', 'Engineering'), ('Commerce', 'Commerce'), ('Other', 'Other')], default='Engineering', max_length=30, verbose_name='Field of Study'),
        ),
    ]
