# Generated by Django 3.0.6 on 2020-12-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_participantprofile_referral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='projects',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
