# Generated by Django 3.0.6 on 2020-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_participantprofile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='projects',
            field=models.TextField(default=''),
        ),
    ]
