version: '3.8'

services: 
    # web:
    #     build: .
    #     container_name: hack_web
    #     command: python manage.py runserver 0.0.0.0:8000
    #     volumes: 
    #         - ./hack21/:/usr/src/hack21/
    #     ports: 
    #         - 8000:8000
    #     env_file: 
    #         - ./.env.dev
    web:
        build: .
        container_name: hack_web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file: 
            - ./.env.dev