version: '3'

services: 
    # web:
    #     build: .
    #     container_name: hack_web
    #     command: python manage.py runserver 0.0.0.0:8000
    #     volumes: 
    #         - ./hack21/:/usr/src/hack21/
    #     ports: 
    #         - 8000:8000
    #     env_file: 
    #         - ./.env.dev
    app:
        build: .
        container_name: hack_app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file: 
            - ./.env.dev
        depends_on: 
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hack_user
            - POSTGRES_PASSWORD=crazy_unicorn
            - POSTGRES_DB=hack_db
        
volumes:
    postgres_data:

