version: '3.7'

services: 
    hack_app:
        build: .
        container_name: hack_app
        command: gunicorn hack21.wsgi:application --bind 0.0.0:8000
        ports: 
            - 8000:8000
        env_file: 
            - ./.env.prod
        depends_on: 
            - db

    db:
        image: postgres:12.0-alpine
        container_name: hack_db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    
volumes:
    postgres_data: