FROM python:3.7-slim-buster
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip


RUN apt-get update \
  # dependencies for building Python packages
  && apt-get install -y build-essential libgdal-dev python3-dev \
  # psycopg2 dependencies
  && apt-get install -y libpq-dev \
  # cleaning up unused files
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /code


RUN mkdir /code/staticfiles
RUN mkdir /code/mediafiles
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt


# create the app user
RUN addgroup --system code \
  && adduser --system --ingroup code code

COPY . /code/

RUN chown -R code:code /code/

USER code

