# Generated by Django 3.0.6 on 2020-07-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_has_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
