# Generated by Django 3.0.6 on 2020-11-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_judge',
            field=models.BooleanField(default=False),
        ),
    ]
