# Generated by Django 3.0.6 on 2020-07-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_has_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_profile',
        ),
    ]
