# Generated by Django 3.0.6 on 2020-11-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201122_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='welcome_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
