# Generated by Django 3.0.6 on 2020-10-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('strength', models.IntegerField(default=0)),
                ('application_status', models.CharField(choices=[('Not Submitted', ' Not Submitted'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Declined', 'Declined'), ('Waitinglist', 'Waitinglist'), ('Accepted', 'Accepted')], max_length=14)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='team_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
