# Generated by Django 3.0.6 on 2020-10-31 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_auto_20201027_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Declined', 'Declined'), ('Waitinglist', 'Waitinglist'), ('Accepted', 'Accepted')], default='Not Submitted', max_length=14)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_team', to='application.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Declined', 'Declined'), ('Waitinglist', 'Waitinglist'), ('Accepted', 'Accepted')], default='Not Submitted', max_length=14)),
                ('members', models.ManyToManyField(related_name='application_user', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_team', to='application.Team')),
            ],
        ),
    ]
