# Generated by Django 3.0.6 on 2020-10-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201031_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
