# Generated by Django 3.0.6 on 2020-10-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_member_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='member_count',
        ),
    ]
