# Generated by Django 3.0.6 on 2020-10-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_application_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_team', to='application.Team'),
        ),
    ]
