# Generated by Django 3.0.6 on 2020-10-31 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0008_auto_20201031_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='application_status',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='request_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Declined', 'Declined'), ('Accepted', 'Submitted')], default='Not Submitted', max_length=14),
        ),
        migrations.AlterField(
            model_name='application',
            name='members',
            field=models.ManyToManyField(related_name='application_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
