# Generated by Django 3.0.6 on 2020-11-11 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0009_auto_20201031_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='request_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Not Submitted', max_length=14),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
