# Generated by Django 3.0.6 on 2020-11-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201126_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted'), ('Declined', 'Declined'), ('Waitinglist', 'Waitinglist'), ('Accepted', 'Accepted')], default='Not Submitted', max_length=14),
        ),
    ]
