# Generated by Django 3.0.6 on 2021-01-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20201130_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='abstract_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='project_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
