# Generated by Django 3.0.6 on 2021-01-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0012_auto_20201130_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.CharField(choices=[('Good Health and Well-being', 'Good Health and Well-being'), ('Quality Education', 'Quality Education'), ('Industry, Innovation and Infrastructure', 'Industry, Innovation and Infrastructure'), ('Life on Land', 'Life on Land'), ('Affordable and Clean Energy', 'Affordable and Clean Energy'), ('Agriculture & Rural Development', 'Agriculture & Rural Development')], max_length=40)),
                ('project_title', models.CharField(max_length=60)),
                ('abstract', models.TextField(max_length=1000)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to='application.Application')),
            ],
        ),
    ]
