# Generated by Django 3.0.6 on 2021-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.CharField(max_length=40)),
                ('project_title', models.CharField(blank=True, max_length=60)),
                ('abstract', models.TextField(max_length=1000)),
            ],
        ),
    ]
