# Generated by Django 3.0.6 on 2021-01-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstract',
            old_name='team',
            new_name='application',
        ),
    ]
