# Generated by Django 3.0.6 on 2021-01-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20210110_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='project_title',
            field=models.CharField(max_length=60),
        ),
    ]
