# Generated by Django 3.0.6 on 2021-01-10 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20210111_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstract',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
