# Generated by Django 3.0.6 on 2021-01-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210111_1427'),
        ('submissions', '0004_auto_20210121_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(verbose_name='Link to video of project')),
                ('code_link', models.URLField(verbose_name='Link To Code')),
                ('ppt_link', models.URLField(verbose_name='Link To Presentation')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='application.Application')),
            ],
        ),
    ]
